@baseUrl = http://localhost:3000

### Lista autores

GET {{baseUrl}}/api/authors

### Cria um novo autor

POST {{baseUrl}}/api/authors 
Content-Type: application/json

{
    "firstName": "Roberto",
    "lastName": "Silva"
}

### Pesquisa autor específico

GET {{baseUrl}}/api/authors/6758488674ca2910a8502340

### Altera autor específico

PUT {{baseUrl}}/api/authors/6758488674ca2910a8502340 
Content-Type: application/json

{
    "lastName": "Rosa"
}

### Exclui autor específico

DELETE {{baseUrl}}/api/authors/6758488674ca2910a8502340