@baseUrl = http://localhost:3000

### Lista autores

GET {{baseUrl}}/api/authors

### Cria um novo autor

POST {{baseUrl}}/api/authors 
Content-Type: application/json

{
    "firstName": "Carlos",
    "lastName": "Silva"
}

### Pesquisa autor específico

GET {{baseUrl}}/api/authors/6743c05c068bea26a7526ac1

### Altera autor específico

PUT {{baseUrl}}/api/authors/6743c05c068bea26a7526ac1 
Content-Type: application/json

{
    "lastName": "Livro 11"
}

### Exclui autor específico

DELETE {{baseUrl}}/api/authors/6743c05c068bea26a7526ac1